Server / Add `leave-room` event
StyleShit/react-live-chat pull request #1
Opened 2022-01-31 17:55 UTC by Omerisra6

2022-01-31 18:20 UTC, StyleShit requested changes

2022-01-31 18:20 UTC, StyleShit commented on server/index.js
> +	});
```suggestion
	socket.on( 'leave-room', () => { 
		handleLeaveRoom( socket );
	} );
```

2022-01-31 18:20 UTC, StyleShit commented on server/event-handlers.js
> + * Handle user data when leaving a room.
```suggestion
 * Handle user when leaving a room.
```

2022-01-31 18:20 UTC, StyleShit commented on server/event-handlers.js
> +
```suggestion
exports.handleLeaveRoom = (  socket  ) => {
	const associatedRoom = users[ socket.id ].room;

	removeUserFromRoom( socket, associatedRoom );
}

```

2022-11-01 07:15 UTC, Omerisra6 commented on server/index.js
> +	});
Never

2022-11-01 07:19 UTC, StyleShit requested changes

2022-11-01 07:19 UTC, StyleShit commented on server/event-handlers.js
>  /**
```suggestion
}

/**
```

2022-11-01 07:19 UTC, StyleShit commented on server/event-handlers.js
> +exports.handleLeaveRoom = (  socket  ) => {
```suggestion
exports.handleLeaveRoom = ( socket ) => {
```

2022-11-01 07:21 UTC, StyleShit approved these changes

2022-11-01 08:41 UTC, merged